title: The Butler
baseline: Your blogging assistant
description: A ready to use static blog, powered by Cecil.
baseurl: https://www.syngths.xyz/
canonicalurl: true
keywords: [The Aarav Syngth Experience, Synthesizers, Synths, Synth, Aarav, Singh]
author: Aarav Singh
date:
  format: F j, Y
  timezone: America/New_York
theme:
  - hyde
  - netlify
  - netlify-cms
hyde:
  sidebar:
    sticky: true # Content to the bottom of the sidebar
  theme: '' # red, orange, yellow, green, cyan, blue, magenta, brown or cecil
  reverse: false # Reverse layout
